# Generated by Django 4.2.14 on 2025-04-30 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='UID',
            new_name='uid',
        ),
    ]
