# Generated by Django 4.2.20 on 2025-05-04 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='prce',
            field=models.PositiveIntegerField(default=1, verbose_name=0),
            preserve_default=False,
        ),
    ]
