# Generated by Django 4.2.20 on 2025-05-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_remove_product_name_product_info_alter_order_filial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
