# Generated by Django 4.2.20 on 2025-05-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_orderitem_prce'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='prce',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
