# Generated by Django 5.1.6 on 2025-02-24 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aloqa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=80)),
                ('subject', models.CharField(max_length=200)),
                ('text', models.TextField()),
            ],
        ),
    ]
