# Generated by Django 5.1.6 on 2025-02-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_filial_order_address_lat_order_address_lng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone_number1',
            field=models.CharField(default=1, max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number2',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
