# Generated by Django 5.1.6 on 2025-02-27 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_order_phone_number1_order_phone_number2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address_lat',
        ),
        migrations.RemoveField(
            model_name='order',
            name='address_lng',
        ),
    ]
