# Generated by Django 5.1.6 on 2025-02-13 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_customuser_is_admin_alter_customuser_is_staff_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_agree',
            new_name='is_agreed',
        ),
    ]
