# Generated by Django 5.1.6 on 2025-02-13 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_is_agree_customuser_is_agreed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_agreed',
            new_name='is_agree',
        ),
    ]
