# Generated by Django 5.1.6 on 2025-02-14 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_category_product_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
